apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec: 
      containers: 
      - name: django-microservice
        image: 825765380838.dkr.ecr.us-east-1.amazonaws.com/appreposfortrainingtrinet:django-microservice-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
